### ISSUE TITLE
How to use these components if event handlers are not implemented?

### ISSUE THREAD

**Issue by kingsleyh** [hamza1311/material-yew#41] opened 2023-02-01 10:50 UTC
Hi

Could someone put an example of how to use these components with events? e.g. 

```rust
 <MatTextField label="Search" value={(*search_query).clone()} >
```
As the user types I want to take the value from the text input and write into an H1 element below the text field

with a regular input field I would do like this - could someone put an example using this MatTextField componet?

```rust
 let search_query = use_state(String::new);

 let oninput = {
        let sq = search_query.clone();
        Callback::from(move |e: InputEvent| {
            let input: HtmlInputElement = e.target_unchecked_into();
            sq.set(input.value());
        })
    };

 yew::html! {
 <div>
   <input type="text" value={(*search_query).clone()} placeholder="Search" {oninput}/>
<h1>{ &*search_query }</h1>
</div>
 }
```

Any help appreciated

**Comment by hamza1311** [comment] 2023-02-10 19:57
Duplicate of #10.

Unfortunately, there's no good solution to this -- the best you could really do is wrap the component in a `<span>`

**Closed by hamza1311** 2023-02-10 19:57 UTC

**Comment by kingsleyh** [comment] 2023-02-10 21:42
It did not work to wrap in a span for the onInput event unfortunately - the component didn't get all the value just the last few characters typed

**Comment by hamza1311** [comment] 2023-02-11 13:00
Oh sorry, I didn't see the `oninput` event. You can use the `oninput` prop: https://docs.rs/material-yew/latest/material_yew/text_inputs/struct.TextFieldProps.html#structfield.oninput
